user_authentication/login_app/urls.py
from django.urls import path
from login_app import views


#TEMPLATE URLS/
app_name = 'login_app'

urlpatterns=[
path('register/',views.register,name='register'),
path('logout/',views.user_logout,name='logout'),
path('other_page/',views.other_page,name='otherpage'),
path('login/',views.user_login,name='user_login'),
]

user_authentication/user_authentication/urls.py
from django.contrib import admin
from django.urls import path,include
from login_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('login_app/',include('login_app.urls')),
]

user_authentication/login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username

user_authentication/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models  import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileform(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

user_authentication/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserProfileform
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'login_app/index.html')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileform(request.POST,request.FILES)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()#saving the user form to the database and grabbing it from the database
            user.set_password(user.password)#hashing the password
            user.save()


            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profle_pic' in request.FILES:#request.FILES grabs image from form
                profile.profle_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:

            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileform()

    return render(request,'login_app/registration.html',
    {'user_form':user_form,
    'profile_form':profile_form,
    'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,'login_app/index.html')
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("invalid login details supplied!")
    else:
        return  render(request,'login_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request,'login_app/index.html')

@login_required
def other_page(request):
    return HttpResponse('Logged In!')

user_authentication/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'login_app:register' %}">Register</a>
        {% if request.user.is_authenticated %}
          <li><a class="nav-item nav-link" href="{% url 'login_app:logout' %}">Logout</a></li>
        {% else %}
          <li><a class="nav-item nav-link" href="{% url 'login_app:user_login' %}">Login</a></li>
        {% endif %}
    </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

  </body>
</html>

user_authentication/templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block content %}


<div class="jumbotron">
    <h1>User Authentication</h1>
</div>
{% endblock %}

user_authentication/templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block content %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'login_app:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
</form>

</div>

{% endblock %}

user_authentication/templates/login_app/registration.html
{% extends "login_app/base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="Submit" name="" value="Register">
  </form>
  {% endif %}

</div>
{% endblock %}